"""AGENTS.md renderer.

Renders a canonical AGENTS.md from:
  - A header with Skein daemon URL and how to recall context
  - Permanent fragments (requirement, procedure, preference) for the scope
  - A "current state" snapshot (≤500 tokens) from state fragments
  - A footer noting the CLAUDE.md shim

``skein sync`` calls this and writes the output to <repo>/AGENTS.md.
The ``<!-- @user -->`` block is preserved across regenerations.
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import List, Optional

from .models import Fragment
from .storage import Storage

# Sentinel block that users can fill with custom content (preserved on sync)
_USER_BLOCK_START = "<!-- @user -->"
_USER_BLOCK_END = "<!-- /@user -->"

# Max characters of each fragment content shown in the state snapshot
_STATE_SNIPPET_CHARS = 300

# Max total tokens (rough 4-char estimate) for the state section
_STATE_MAX_CHARS = 2000


def render_agents_md(
    scope_handle: str,
    storage: Storage,
    *,
    daemon_url: str = "http://127.0.0.1:8765",
    project_name: Optional[str] = None,
    existing_content: Optional[str] = None,
) -> str:
    """Render AGENTS.md for a scope.

    If ``existing_content`` is provided, any ``<!-- @user --> ... <!-- /@user -->``
    block is extracted and preserved in the output.
    """
    scope = storage.get_scope(scope_handle)
    if not scope:
        return _minimal_agents_md(scope_handle, daemon_url)

    # Extract user block from existing file (preserve manual additions)
    user_block = _extract_user_block(existing_content or "")

    # Gather permanent fragments
    all_frags = storage.list_fragments(scope_id=scope.id, include_stale=False, limit=200)
    permanent_types = {"requirement", "procedure", "preference"}
    permanent = [f for f in all_frags if f.type in permanent_types]
    state_frags = [f for f in all_frags if f.type == "state"]
    decision_frags = [f for f in all_frags if f.type == "decision"]

    name = project_name or scope.name or scope_handle
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: List[str] = []

    # ---- Header ----
    lines.append(f"# AGENTS.md — {name}")
    lines.append("")
    lines.append(f"> **Generated by Skein** at {now}. Do not edit this file directly;")
    lines.append("> run `skein sync` to regenerate. Add custom content in the `<!-- @user -->` block.")
    lines.append("")
    lines.append("## Skein context bus")
    lines.append("")
    lines.append(f"This project uses [Skein]({daemon_url}) for cross-LLM context sharing.")
    lines.append(f"MCP endpoint: `{daemon_url}/mcp`")
    lines.append("")
    lines.append("**Before starting work, call `recall` to load relevant context:**")
    lines.append("```")
    lines.append(f"# MCP tool call (Claude Code, Cursor, Codex, Gemini CLI, etc.)")
    lines.append(f'recall(query="<your task description>", scope="{scope_handle}")')
    lines.append("```")
    lines.append("**After significant decisions, call `remember`:**")
    lines.append("```")
    lines.append(f'remember(content="<what you decided>", type="decision", scope="{scope_handle}")')
    lines.append("```")
    lines.append("")

    # ---- Requirements ----
    reqs = [f for f in permanent if f.type == "requirement"]
    if reqs:
        lines.append("## Requirements")
        lines.append("")
        for frag in reqs:
            _append_fragment_bullet(lines, frag)
        lines.append("")

    # ---- Decisions ----
    if decision_frags:
        lines.append("## Active decisions")
        lines.append("")
        for frag in decision_frags[:20]:  # cap at 20
            _append_fragment_bullet(lines, frag)
        lines.append("")

    # ---- Preferences ----
    prefs = [f for f in permanent if f.type == "preference"]
    if prefs:
        lines.append("## Preferences")
        lines.append("")
        for frag in prefs:
            _append_fragment_bullet(lines, frag)
        lines.append("")

    # ---- Procedures ----
    procs = [f for f in permanent if f.type == "procedure"]
    if procs:
        lines.append("## Procedures")
        lines.append("")
        for frag in procs:
            lines.append(f"### {frag.territory or 'General'}")
            lines.append("")
            lines.append(frag.content)
            lines.append("")

    # ---- Current state snapshot ----
    if state_frags:
        lines.append("## Current state")
        lines.append("")
        total_chars = 0
        for frag in sorted(state_frags, key=lambda f: f.updated_at, reverse=True):
            if total_chars >= _STATE_MAX_CHARS:
                lines.append(f"*… {len(state_frags) - state_frags.index(frag)} more state fragments — call `recall` for full context.*")
                break
            snippet = frag.content[:_STATE_SNIPPET_CHARS]
            if len(frag.content) > _STATE_SNIPPET_CHARS:
                snippet += "…"
            territory_prefix = f"**{frag.territory}**: " if frag.territory else ""
            lines.append(f"- {territory_prefix}{snippet}")
            total_chars += len(snippet)
        lines.append("")

    # ---- User block ----
    lines.append(_USER_BLOCK_START)
    if user_block.strip():
        lines.append(user_block.strip())
    else:
        lines.append("<!-- Add any manual context here. This block is preserved across `skein sync`. -->")
    lines.append(_USER_BLOCK_END)
    lines.append("")

    return "\n".join(lines)


def render_claude_md_shim() -> str:
    """Return a CLAUDE.md that is a single @AGENTS.md shim."""
    return "@AGENTS.md\n"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _append_fragment_bullet(lines: List[str], frag: Fragment) -> None:
    territory = f" *(territory: {frag.territory})*" if frag.territory else ""
    tags = f" [tags: {', '.join(frag.tags)}]" if frag.tags else ""
    lines.append(f"- {frag.content}{territory}{tags}")


def _extract_user_block(content: str) -> str:
    """Extract content between <!-- @user --> and <!-- /@user --> markers.

    The markers MUST appear at the start of a line. The header documentation
    line ``Add custom content in the `<!-- @user -->` block`` contains a
    literal ``<!-- @user -->`` for the user to read; without the anchor the
    regex would match from there and absorb the entire document on every
    ``skein sync``, growing AGENTS.md unboundedly. (Reproduced live: a
    project's AGENTS.md grew from 1 KB to 100+ KB after 11 syncs.)
    """
    pattern = re.compile(
        r"^<!--\s*@user\s*-->[ \t]*\n(.*?)^<!--\s*/@user\s*-->",
        re.DOTALL | re.MULTILINE,
    )
    m = pattern.search(content)
    return m.group(1) if m else ""


def _minimal_agents_md(scope_handle: str, daemon_url: str) -> str:
    return (
        f"# AGENTS.md\n\n"
        f"> Skein daemon: {daemon_url}/mcp\n\n"
        f"Scope `{scope_handle}` not found. Run `skein init` to set up.\n"
    )
