"""AGENTS.md renderer + writer.

Renders a canonical AGENTS.md from:
  - A header with Skein daemon URL and how to recall context
  - Permanent fragments (requirement, procedure, preference) for the scope
  - A "current state" snapshot (≤500 tokens) from state fragments
  - A footer noting the CLAUDE.md shim

The ``<!-- @user -->`` block is preserved across regenerations.

ADR-002 / iter 26: the daemon now keeps AGENTS.md in sync automatically.
``sync_agents_md_for_project`` is the single write path — called by both
``skein up`` for first-render and by the daemon's auto-sync loop (server.py)
on every interval. It hashes the rendered bytes and skips the disk write
when nothing changed, so the file doesn't get touched (and the watcher
doesn't get tickled) on every sweep.
"""
from __future__ import annotations

import hashlib
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .models import Fragment
from .storage import Storage

logger = logging.getLogger("skein.agents_md")

# Sentinel block that users can fill with custom content (preserved on sync)
_USER_BLOCK_START = "<!-- @user -->"
_USER_BLOCK_END = "<!-- /@user -->"

# Max characters of each fragment content shown in the state snapshot
_STATE_SNIPPET_CHARS = 300

# Max total tokens (rough 4-char estimate) for the state section
_STATE_MAX_CHARS = 2000


def render_agents_md(
    scope_handle: str,
    storage: Storage,
    *,
    daemon_url: str = "http://127.0.0.1:8765",
    project_name: Optional[str] = None,
    existing_content: Optional[str] = None,
) -> str:
    """Render AGENTS.md for a scope.

    If ``existing_content`` is provided, any ``<!-- @user --> ... <!-- /@user -->``
    block is extracted and preserved in the output.
    """
    scope = storage.get_scope(scope_handle)
    if not scope:
        return _minimal_agents_md(scope_handle, daemon_url)

    # Extract user block from existing file (preserve manual additions)
    user_block = _extract_user_block(existing_content or "")

    # Gather permanent fragments
    all_frags = storage.list_fragments(scope_id=scope.id, include_stale=False, limit=200)
    permanent_types = {"requirement", "procedure", "preference"}
    permanent = [f for f in all_frags if f.type in permanent_types]
    state_frags = [f for f in all_frags if f.type == "state"]
    decision_frags = [f for f in all_frags if f.type == "decision"]

    name = project_name or scope.name or scope_handle
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []

    # ---- Header ----
    lines.append(f"# AGENTS.md — {name}")
    lines.append("")
    lines.append(f"> **Generated by Skein** at {now}. Do not edit this file directly;")
    lines.append("> the daemon regenerates it automatically when fragments change. Add custom content in the `<!-- @user -->` block.")
    lines.append("")
    lines.append("## How to use Skein in this project — read BEFORE you do anything else")
    lines.append("")
    lines.append("Skein is the fastest path to context here. Concrete numbers:")
    lines.append(f"- `project_briefing()` returns the project dashboard in ONE call — <50ms, ~300 tokens.")
    lines.append(f"- `recall(\"<your task>\")` returns top-K relevant fragments — <100ms, ~30 tokens per fragment.")
    lines.append("- For comparison: reading 3 source files for the same context costs 3000+ tokens, 5+ round trips, and often misses the WHY.")
    # Iter 23: surface the privacy story when a local embedding provider is active.
    # The active provider is read from config — if config can't be loaded for any
    # reason, skip the line silently rather than block the render.
    try:
        from .config import get_config
        _active_provider = get_config().embedding_provider
        if _active_provider in ("fastembed", "bm25", "hash"):
            lines.append("- Embeddings run locally — no API key needed, your code never leaves this machine.")
    except Exception:
        pass
    lines.append("")
    lines.append("**Default behavior for any task on this project:**")
    lines.append("1. Call `project_briefing()` first if you need the project overview (what's it doing, where it's at, what changed lately).")
    lines.append("2. Call `recall(\"<task>\")` for context relevant to your specific task.")
    lines.append("3. Only fall back to `read_file` / `grep` for code-execution details that semantic recall can't give.")
    lines.append("4. After any non-obvious decision, call `remember(...)` or `note_decision(...)` so other tools (and you in a future session) inherit it.")
    lines.append("")
    lines.append("Each `recall` result carries a `quality` bucket: `high` / `medium` / `low` / `none`. If the top result is `quality=none`, Skein has nothing high-signal for that query — fall back to source. Honest no-knowledge is more useful than weak hits.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Skein context bus")
    lines.append("")
    lines.append(f"This project uses [Skein]({daemon_url}) for cross-LLM context sharing.")
    lines.append(f"MCP endpoint: `{daemon_url}/mcp`")
    lines.append("")
    lines.append("Quick reference (MCP tool calls — work in Claude Code, Cursor, Codex, Gemini CLI, Antigravity, etc.):")
    lines.append("```")
    lines.append(f'project_briefing(scope="{scope_handle}")              # ONE-call dashboard')
    lines.append(f'recall(query="<task>", scope="{scope_handle}")        # task-specific context')
    lines.append(f'remember(content="<what you decided>", type="decision", scope="{scope_handle}")')
    lines.append("```")
    lines.append("")

    # ---- Project facts (auto-extracted, iter 14.1 + 14.2) ----
    # Surface the implicit context Skein has learned from the codebase + chat
    # transcripts. These auto-extracted facts are what every LLM should start
    # with before answering anything — they capture stack, conventions, and
    # decisions that aren't in any one source file.
    fact_frags = [
        f for f in all_frags
        if f.type == "fact" and f.extraction_method != "explicit"
    ]
    if fact_frags:
        lines.append("## Project facts (auto-detected)")
        lines.append("")
        lines.append(
            "Skein extracted these facts from your codebase and recent AI "
            "conversations. Treat them as authoritative project context."
        )
        lines.append("")
        # Group by source tool for clarity
        by_tool: dict[str, list] = {}
        for f in fact_frags:
            tool = f.created_by_tool or "unknown"
            by_tool.setdefault(tool, []).append(f)
        for tool, items in by_tool.items():
            label = {
                "code-scanner": "From the codebase",
                "transcript-claude": "From recent Claude Code sessions",
                "transcript-cursor": "From recent Cursor sessions",
            }.get(tool, f"From {tool}")
            lines.append(f"### {label}")
            lines.append("")
            for f in items[:30]:  # cap per source
                _append_fragment_bullet(lines, f)
            if len(items) > 30:
                lines.append(f"*… and {len(items) - 30} more from {tool} — call `recall` for the full list.*")
            lines.append("")

    # ---- Requirements ----
    reqs = [f for f in permanent if f.type == "requirement"]
    if reqs:
        lines.append("## Requirements")
        lines.append("")
        for frag in reqs:
            _append_fragment_bullet(lines, frag)
        lines.append("")

    # ---- Decisions ----
    if decision_frags:
        lines.append("## Active decisions")
        lines.append("")
        for frag in decision_frags[:20]:  # cap at 20
            _append_fragment_bullet(lines, frag)
        lines.append("")

    # ---- Preferences ----
    prefs = [f for f in permanent if f.type == "preference"]
    if prefs:
        lines.append("## Preferences")
        lines.append("")
        for frag in prefs:
            _append_fragment_bullet(lines, frag)
        lines.append("")

    # ---- Procedures ----
    procs = [f for f in permanent if f.type == "procedure"]
    if procs:
        lines.append("## Procedures")
        lines.append("")
        for frag in procs:
            lines.append(f"### {frag.territory or 'General'}")
            lines.append("")
            lines.append(frag.content)
            lines.append("")

    # ---- Current state snapshot ----
    if state_frags:
        lines.append("## Current state")
        lines.append("")
        total_chars = 0
        for frag in sorted(state_frags, key=lambda f: f.updated_at, reverse=True):
            if total_chars >= _STATE_MAX_CHARS:
                lines.append(f"*… {len(state_frags) - state_frags.index(frag)} more state fragments — call `recall` for full context.*")
                break
            snippet = frag.content[:_STATE_SNIPPET_CHARS]
            if len(frag.content) > _STATE_SNIPPET_CHARS:
                snippet += "…"
            territory_prefix = f"**{frag.territory}**: " if frag.territory else ""
            lines.append(f"- {territory_prefix}{snippet}")
            total_chars += len(snippet)
        lines.append("")

    # ---- User block ----
    lines.append(_USER_BLOCK_START)
    if user_block.strip():
        lines.append(user_block.strip())
    else:
        lines.append("<!-- Add any manual context here. This block is preserved across daemon-side regeneration. -->")
    lines.append(_USER_BLOCK_END)
    lines.append("")

    return "\n".join(lines)


def render_claude_md_shim() -> str:
    """Return a CLAUDE.md that is a single @AGENTS.md shim."""
    return "@AGENTS.md\n"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _append_fragment_bullet(lines: list[str], frag: Fragment) -> None:
    territory = f" *(territory: {frag.territory})*" if frag.territory else ""
    tags = f" [tags: {', '.join(frag.tags)}]" if frag.tags else ""
    lines.append(f"- {frag.content}{territory}{tags}")


def _extract_user_block(content: str) -> str:
    """Extract content between <!-- @user --> and <!-- /@user --> markers.

    The markers MUST appear at the start of a line. The header documentation
    line ``Add custom content in the `<!-- @user -->` block`` contains a
    literal ``<!-- @user -->`` for the user to read; without the anchor the
    regex would match from there and absorb the entire document on every
    ``skein sync``, growing AGENTS.md unboundedly. (Reproduced live: a
    project's AGENTS.md grew from 1 KB to 100+ KB after 11 syncs.)
    """
    pattern = re.compile(
        r"^<!--\s*@user\s*-->[ \t]*\n(.*?)^<!--\s*/@user\s*-->",
        re.DOTALL | re.MULTILINE,
    )
    m = pattern.search(content)
    return m.group(1) if m else ""


def _minimal_agents_md(scope_handle: str, daemon_url: str) -> str:
    return (
        f"# AGENTS.md\n\n"
        f"> Skein daemon: {daemon_url}/mcp\n\n"
        f"Scope `{scope_handle}` not found. Run `skein init` to set up.\n"
    )


def sync_agents_md_for_project(
    *,
    storage: Storage,
    scope_handle: str,
    repo_root: Path,
    daemon_url: str,
    write_claude_md_shim: bool = True,
) -> bool:
    """Render and (if changed) write AGENTS.md for a single project.

    Used by both ``skein up`` and the daemon auto-sync loop. Returns True
    if the file was rewritten, False if nothing changed. Idempotent: the
    rendered hash is compared to the on-disk file's hash so an unmodified
    file is left exactly alone (preserving its mtime and not tickling
    file watchers).
    """
    agents_md_path = repo_root / "AGENTS.md"
    existing = agents_md_path.read_text() if agents_md_path.exists() else None
    rendered = render_agents_md(
        scope_handle=scope_handle,
        storage=storage,
        daemon_url=daemon_url,
        existing_content=existing,
    )
    rendered_hash = hashlib.sha256(rendered.encode("utf-8")).hexdigest()
    on_disk_hash = (
        hashlib.sha256(existing.encode("utf-8")).hexdigest()
        if existing is not None else None
    )
    if on_disk_hash == rendered_hash:
        # Update the state row anyway so the daemon doesn't keep re-rendering
        # when the file is already correct — cheap idempotent write.
        storage.upsert_agents_md_state(scope_handle, str(agents_md_path), rendered_hash)
        return False

    agents_md_path.parent.mkdir(parents=True, exist_ok=True)
    agents_md_path.write_text(rendered)
    if write_claude_md_shim:
        claude_md_path = repo_root / "CLAUDE.md"
        if not claude_md_path.exists():
            claude_md_path.write_text("@AGENTS.md\n")
    storage.upsert_agents_md_state(scope_handle, str(agents_md_path), rendered_hash)
    return True
