"""Bearer-token authentication for the Skein daemon.

v1: single-user local bearer token.  The token is stored in
~/.config/skein/config.json and generated by ``skein init``.

Every authenticated request synthesises an identity context:
    user_id      = config.bearer_token[:8]  (stable prefix as a human-readable key)
    handle       = "user:<token_prefix>"
    agent_id     = extracted from X-Skein-Agent header (optional, defaults to "cli")
    scope        = target scope from request path / query

The auth layer also auto-creates the identity row on first authentication,
so the system bootstraps without a separate "register" step.

ADR-006: Claims shape (user_id, project_id, agent_id, scope) baked in now.
Cloud swap: replace bearer-decoder with JWT-decoder; claims shape stays.
"""
from __future__ import annotations

import hashlib
import logging
import secrets
from functools import lru_cache
from typing import Optional

from fastapi import Depends, Header, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from .models import Identity, IdentityCreate

logger = logging.getLogger("skein.auth")

# FastAPI HTTP Bearer scheme (auto-adds WWW-Authenticate header on 401)
_bearer_scheme = HTTPBearer(auto_error=False)


def generate_token() -> str:
    """Generate a cryptographically secure 32-byte hex token."""
    return secrets.token_hex(32)


def token_prefix(token: str) -> str:
    """Stable 8-char human-readable prefix derived from the token."""
    return hashlib.sha256(token.encode()).hexdigest()[:8]


# ---------------------------------------------------------------------------
# FastAPI dependencies
# ---------------------------------------------------------------------------

class AuthContext:
    """Resolved identity for the current request."""

    def __init__(
        self,
        identity: Identity,
        agent_id: str,
        raw_token: str,
    ) -> None:
        self.identity = identity
        self.agent_id = agent_id
        self.raw_token = raw_token

    @property
    def user_id(self) -> str:
        return self.identity.id

    @property
    def handle(self) -> str:
        return self.identity.handle


async def get_auth(
    request: Request,
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(_bearer_scheme),
    x_skein_agent: Optional[str] = Header(None, alias="X-Skein-Agent"),
) -> AuthContext:
    """FastAPI dependency — validates bearer token and returns AuthContext."""
    from .config import get_config
    from .dependencies import get_storage

    cfg = get_config()

    # Bearer token via Authorization header only — query params would leak the
    # credential into proxy/CDN access logs and shell history.
    raw_token: Optional[str] = None
    if credentials and credentials.scheme.lower() == "bearer":
        raw_token = credentials.credentials

    if not raw_token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing bearer token. Set Authorization: Bearer <token>",
            headers={"WWW-Authenticate": "Bearer"},
        )

    if not cfg.bearer_token:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Skein not initialised. Run `skein init` first.",
        )

    if not secrets.compare_digest(raw_token, cfg.bearer_token):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid bearer token",
            headers={"WWW-Authenticate": "Bearer"},
        )

    # Auto-create identity on first auth
    storage = get_storage()
    handle = f"user:{token_prefix(raw_token)}"
    identity = storage.get_or_create_identity(IdentityCreate(
        handle=handle,
        type="user",
        name="local-user",
    ))

    agent_id = x_skein_agent or "cli"
    return AuthContext(identity=identity, agent_id=agent_id, raw_token=raw_token)


# Convenience alias used throughout routers
RequireAuth = Depends(get_auth)
